Update master_app-nyforvarvslistan-dev.yml

diff --git a/.github/workflows/master_app-nyforvarvslistan-dev.yml b/.github/workflows/master_app-nyforvarvslistan-dev.yml
--- a/.github/workflows/master_app-nyforvarvslistan-dev.yml
+++ b/.github/workflows/master_app-nyforvarvslistan-dev.yml
@@ -38,6 +38,13 @@ jobs:
           pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
           dotnet build --configuration Release --output ./output
           popd
+
+      - name: Check if Dewey_SAB.txt is in the output directory
+        run: |
+          if [ ! -f "./output/Dewey_SAB.txt" ]; then
+            echo "Dewey_SAB.txt is missing from the output directory"
+            exit 1
+          fi
       
       - name: Login to Azure
         uses: azure/login@v1
